
name: Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write   
  contents: read

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GCP Authenticate
        uses: 'google-github-actions/auth@v3'
        with:
          workload_identity_provider: 'projects/343090954560/locations/global/workloadIdentityPools/github-terraform-ci/providers/github'
          service_account: 'gcp-terraform-ci@gke-learning-470213.iam.gserviceaccount.com'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0

      - name: Terraform Init
        working-directory: ./tf-files
        run: terraform init

      - name: Terraform Plan
        working-directory: ./tf-files
        run: terraform plan 

  terraform-apply:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GCP Authenticate
        uses: 'google-github-actions/auth@v3'
        with:
          workload_identity_provider: 'projects/343090954560/locations/global/workloadIdentityPools/github-terraform-ci/providers/github'
          service_account: 'gcp-terraform-ci@gke-learning-470213.iam.gserviceaccount.com'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0

      - name: Terraform Init
        working-directory: ./tf-files
        run: terraform init

      - name: Terraform Apply
        working-directory: ./tf-files
        run: terraform apply -auto-approve